# Enable cross-compilation
set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)
# Only look libraries etc. in the sysroot, but never look there for programs
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
# Disable unsupported alpaqa features
set(ALPAQA_WITH_CASADI Off CACHE BOOL "" FORCE)
set(ALPAQA_WITH_DL Off CACHE BOOL "" FORCE)
set(ALPAQA_WITH_CUTEST Off CACHE BOOL "" FORCE)
set(ALPAQA_WITH_DRIVERS Off CACHE BOOL "" FORCE)
set(ALPAQA_WITH_OCP Off CACHE BOOL "" FORCE)
set(BUILD_TESTING Off CACHE BOOL "" FORCE)

set(CMAKE_CXX_EXTENSIONS On)
set(CMAKE_C_EXTENSIONS On)
set(CMAKE_INTERPROCEDURAL_OPTIMIZATION Off)
set(CMAKE_Fortran_COMPILER "NOTFOUND" CACHE FILEPATH "" FORCE)

set(PICO_CXX_ENABLE_EXCEPTIONS On CACHE INTERNAL "")
set(PICO_CXX_ENABLE_RTTI Off CACHE INTERNAL "")

include("$ENV{PICO_SDK_PATH}/cmake/preload/toolchains/pico_arm_gcc.cmake")
include($ENV{PICO_SDK_PATH}/pico_sdk_init.cmake)
