include(InstallRequiredSystemLibraries)
set(CPACK_PACKAGE_VERSION_MAJOR "${PROJECT_VERSION_MAJOR}")
set(CPACK_PACKAGE_VERSION_MINOR "${PROJECT_VERSION_MINOR}")
set(CPACK_PACKAGE_VERSION_PATCH "${PROJECT_VERSION_PATCH}")
set(CPACK_PACKAGE_VERSION "${PROJECT_VERSION}${PY_VERSION_SUFFIX}")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "${PROJECT_NAME}")
set(CPACK_PACKAGE_CHECKSUM "SHA256")
set(CPACK_RESOURCE_FILE_LICENSE "${PROJECT_SOURCE_DIR}/LICENSE")
set(CPACK_PACKAGE_DESCRIPTION_FILE "${PROJECT_SOURCE_DIR}/cmake/description.txt")
SET(CPACK_DEBIAN_PACKAGE_MAINTAINER "Pieter Pas <pieter.p.dev@outlook.com>")
if (NOT WIN32)
    set(CPACK_SYSTEM_NAME "${CMAKE_SYSTEM_NAME}-${CMAKE_SYSTEM_PROCESSOR}")
endif()
set(CPACK_DEBIAN_FILE_NAME DEB-DEFAULT)
set(CPACK_VERBATIM_VARIABLES On)

# Package components
set(CPACK_DEB_COMPONENT_INSTALL On)
set(CPACK_COMPONENTS_ALL "lib;dev;dl_dev;debug;bin;extra;extra_dev")
if (ALPAQA_WITH_CASADI)
    list(APPEND CPACK_COMPONENTS_ALL "casadi" "casadi_dev")
endif()
if (ALPAQA_WITH_MATLAB)
    list(APPEND CPACK_COMPONENTS_ALL "matlab")
endif()

set(CPACK_DEBIAN_LIB_PACKAGE_NAME "libalpaqa")
set(CPACK_DEBIAN_LIB_DISPLAY_NAME "alpaqa libraries")
set(CPACK_DEBIAN_LIB_DESCRIPTION "Shared libraries needed to run applications that use alpaqa.")
set(CPACK_DEBIAN_LIB_GROUP "Runtime")
set(CPACK_DEBIAN_LIB_PACKAGE_DEPENDS "libc6 (>= 2.17), libgfortran5 (>= 10), libquadmath0 (>= 10)")

set(CPACK_DEBIAN_DEV_PACKAGE_NAME "libalpaqa-dev")
set(CPACK_DEBIAN_DEV_DISPLAY_NAME "alpaqa development files")
set(CPACK_DEBIAN_DEV_DESCRIPTION "C++ header files and CMake target files to develop software that uses alpaqa.")
set(CPACK_DEBIAN_DEV_GROUP "Development")
set(CPACK_DEBIAN_DEV_PACKAGE_DEPENDS "libalpaqa (= ${CPACK_PACKAGE_VERSION}), libalpaqa-dl-dev (= ${CPACK_PACKAGE_VERSION})")
set(CPACK_DEBIAN_DEV_PACKAGE_SUGGESTS "libeigen3-dev (>= 3.4.0), libeigen3-dev (<< 3.4.1)")
set(CPACK_COMPONENT_DEV_DEPENDS "lib;dl_dev")

set(CPACK_DEBIAN_DL_DEV_PACKAGE_NAME "libalpaqa-dl-dev")
set(CPACK_DEBIAN_DL_DEV_DISPLAY_NAME "alpaqa dynamic loading development files")
set(CPACK_DEBIAN_DL_DEV_DESCRIPTION "C header files needed to compile problem specifications that can be dynamically loaded by alpaqa.")
set(CPACK_DEBIAN_DL_DEV_GROUP "Development")
set(CPACK_DEBIAN_DL_DEV_PACKAGE_DEPENDS "")
set(CPACK_DEBIAN_DL_DEV_PACKAGE_SUGGESTS "libalpaqa-dev (= ${CPACK_PACKAGE_VERSION})")

set(CPACK_DEBIAN_DEBUG_PACKAGE_NAME "libalpaqa-debug")
set(CPACK_DEBIAN_DEBUG_DISPLAY_NAME "alpaqa debug symbols")
set(CPACK_DEBIAN_DEBUG_DESCRIPTION "Debug symbols for the alpaqa tools and libraries.")
set(CPACK_DEBIAN_DEBUG_GROUP "Development")
set(CPACK_DEBIAN_DEBUG_PACKAGE_DEPENDS "libalpaqa (= ${CPACK_PACKAGE_VERSION})")
set(CPACK_COMPONENT_DEBUG_DEPENDS "lib")
set(CPACK_COMPONENT_DEBUG_DISABLED On)

set(CPACK_DEBIAN_BIN_PACKAGE_NAME "libalpaqa-tools")
set(CPACK_DEBIAN_BIN_DISPLAY_NAME "alpaqa command-line tools")
set(CPACK_DEBIAN_BIN_DESCRIPTION "Command line utilities such as alpaqa-driver, which can be used to invoke the solvers directly, without the need to write any C++ code.")
set(CPACK_DEBIAN_BIN_GROUP "Tools")
set(CPACK_DEBIAN_BIN_PACKAGE_DEPENDS "libalpaqa-extra (= ${CPACK_PACKAGE_VERSION})")
set(CPACK_DEBIAN_BIN_PACKAGE_RECOMMENDS "bash-completion")
set(CPACK_COMPONENT_BIN_DEPENDS "extra")
if (ALPAQA_WITH_CASADI)
    string(APPEND CPACK_DEBIAN_BIN_PACKAGE_DEPENDS ", libalpaqa-casadi (= ${CPACK_PACKAGE_VERSION})")
    list(APPEND CPACK_COMPONENT_BIN_DEPENDS "casadi")
endif()

set(CPACK_DEBIAN_MATLAB_PACKAGE_NAME "libalpaqa-matlab")
set(CPACK_DEBIAN_MATLAB_DISPLAY_NAME "alpaqa Matlab interface")
set(CPACK_DEBIAN_MATLAB_DESCRIPTION "The Matlab/MEX interface to the alpaqa solvers.")
set(CPACK_DEBIAN_MATLAB_GROUP "Extra")
set(CPACK_DEBIAN_MATLAB_PACKAGE_DEPENDS "libalpaqa-casadi (= ${CPACK_PACKAGE_VERSION})")
set(CPACK_COMPONENT_MATLAB_DEPENDS "casadi")
set(CPACK_COMPONENT_MATLAB_DISABLED On)

set(CPACK_DEBIAN_CASADI_PACKAGE_NAME "libalpaqa-casadi")
set(CPACK_DEBIAN_CASADI_DISPLAY_NAME "alpaqa loaders for CasADi problems")
set(CPACK_DEBIAN_CASADI_DESCRIPTION "Classes for loading problems defined using CasADi functions.")
set(CPACK_DEBIAN_CASADI_GROUP "Extra")
set(CPACK_DEBIAN_CASADI_PACKAGE_DEPENDS "libalpaqa (= ${CPACK_PACKAGE_VERSION})")
set(CPACK_COMPONENT_CASADI_DEPENDS "lib")

set(CPACK_DEBIAN_CASADI_DEV_PACKAGE_NAME "libalpaqa-casadi-dev")
set(CPACK_DEBIAN_CASADI_DEV_DISPLAY_NAME "alpaqa development files for the CasADi loaders")
set(CPACK_DEBIAN_CASADI_DEV_DESCRIPTION "C++ header files and CMake target files to develop software that uses the CasADi loaders.")
set(CPACK_DEBIAN_CASADI_DEV_GROUP "Development")
set(CPACK_DEBIAN_CASADI_DEV_PACKAGE_DEPENDS "libalpaqa-casadi (= ${CPACK_PACKAGE_VERSION}), libalpaqa-dev (= ${CPACK_PACKAGE_VERSION})")
set(CPACK_COMPONENT_CASADI_DEV_DEPENDS "casadi;dev")

set(CPACK_DEBIAN_EXTRA_PACKAGE_NAME "libalpaqa-extra")
set(CPACK_DEBIAN_EXTRA_DISPLAY_NAME "Extra alpaqa solvers and loaders")
set(CPACK_DEBIAN_EXTRA_DESCRIPTION "Interfaces to additional solvers and problem loaders.")
set(CPACK_DEBIAN_EXTRA_GROUP "Extra")
set(CPACK_DEBIAN_EXTRA_PACKAGE_DEPENDS "libalpaqa (= ${CPACK_PACKAGE_VERSION})")
set(CPACK_COMPONENT_EXTRA_DEPENDS "lib")

set(CPACK_DEBIAN_EXTRA_DEV_PACKAGE_NAME "libalpaqa-extra-dev")
set(CPACK_DEBIAN_EXTRA_DEV_DISPLAY_NAME "Extra alpaqa solvers and loaders development files")
set(CPACK_DEBIAN_EXTRA_DEV_DESCRIPTION "C++ header files and CMake target files to develop software that uses the additional solvers and problem loaders.")
set(CPACK_DEBIAN_EXTRA_DEV_GROUP "Development")
set(CPACK_DEBIAN_EXTRA_DEV_PACKAGE_DEPENDS "libalpaqa-extra (= ${CPACK_PACKAGE_VERSION}), libalpaqa-dev (= ${CPACK_PACKAGE_VERSION})")
set(CPACK_COMPONENT_EXTRA_DEV_DEPENDS "extra;dev")

# Source packages
set(CPACK_SOURCE_PACKAGE_FILE_NAME "${PROJECT_NAME}-${CPACK_PACKAGE_VERSION}")
set(CPACK_SOURCE_GENERATOR "TGZ;ZIP")
set(CPACK_SOURCE_IGNORE_FILES
    \\.git/
    build/
)
include(CPack)
