include(InstallRequiredSystemLibraries)
set(CPACK_PACKAGE_VERSION_MAJOR "${PROJECT_VERSION_MAJOR}")
set(CPACK_PACKAGE_VERSION_MINOR "${PROJECT_VERSION_MINOR}")
set(CPACK_PACKAGE_VERSION_PATCH "${PROJECT_VERSION_PATCH}${PY_VERSION_SUFFIX}")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "${PROJECT_NAME}")
set(CPACK_PACKAGE_CHECKSUM "SHA256")
set(CPACK_RESOURCE_FILE_LICENSE "${PROJECT_SOURCE_DIR}/LICENSE")
set(CPACK_PACKAGE_DESCRIPTION_FILE "${PROJECT_SOURCE_DIR}/cmake/description.txt")
SET(CPACK_DEBIAN_PACKAGE_MAINTAINER "Pieter Pas <pieter.p.dev@outlook.com>")
if (NOT WIN32)
    set(CPACK_SYSTEM_NAME "${CMAKE_SYSTEM_NAME}-${CMAKE_SYSTEM_PROCESSOR}")
endif()
set(CPACK_DEBIAN_FILE_NAME DEB-DEFAULT)
set(CPACK_VERBATIM_VARIABLES On)
# Package components
set(CPACK_COMPONENTS_ALL "lib;dev;dl_dev;debug;bin;matlab;casadi;extra")
set(CPACK_DEB_COMPONENT_INSTALL On)
set(CPACK_DEBIAN_LIB_PACKAGE_NAME "libalpaqa")
set(CPACK_DEBIAN_LIB_DISPLAY_NAME "Libraries")
set(CPACK_DEBIAN_LIB_DESCRIPTION "Shared libraries needed to run applications that use alpaqa")
set(CPACK_DEBIAN_LIB_GROUP "Runtime")
set(CPACK_DEBIAN_DEV_PACKAGE_NAME "libalpaqa-dev")
set(CPACK_DEBIAN_DEV_DISPLAY_NAME "Development files")
set(CPACK_DEBIAN_DEV_DESCRIPTION "C++ header files and CMake target files to develop software that uses alpaqa")
set(CPACK_DEBIAN_DEV_GROUP "Development")
set(CPACK_DEBIAN_DL_DEV_PACKAGE_NAME "libalpaqa-dl-dev")
set(CPACK_DEBIAN_DL_DEV_DISPLAY_NAME "Dynamic loading development files")
set(CPACK_DEBIAN_DL_DEV_DESCRIPTION "C header files needed to compile problem specifications that can be dynamically loaded by alpaqa")
set(CPACK_DEBIAN_DL_DEV_GROUP "Development")
set(CPACK_DEBIAN_DEBUG_PACKAGE_NAME "libalpaqa-debug")
set(CPACK_DEBIAN_DEBUG_DISPLAY_NAME "Debug symbols")
set(CPACK_DEBIAN_DEBUG_DESCRIPTION "Debug symbols for the alpaqa tools and libraries")
set(CPACK_DEBIAN_DEBUG_GROUP "Development")
set(CPACK_DEBIAN_BIN_PACKAGE_NAME "libalpaqa-tools")
set(CPACK_DEBIAN_BIN_DISPLAY_NAME "Tools")
set(CPACK_DEBIAN_BIN_DESCRIPTION "Command line utilities such as alpaqa-driver, which can be used to invoke the solvers directly, without the need to write any C++ code")
set(CPACK_DEBIAN_BIN_GROUP "Tools")
set(CPACK_DEBIAN_MATLAB_PACKAGE_NAME "libalpaqa-matlab")
set(CPACK_DEBIAN_MATLAB_DISPLAY_NAME "Matlab interface")
set(CPACK_DEBIAN_MATLAB_DESCRIPTION "The Matlab/MEX interface to the alpaqa solvers")
set(CPACK_DEBIAN_MATLAB_GROUP "Extra")
set(CPACK_DEBIAN_CASADI_PACKAGE_NAME "libalpaqa-casadi")
set(CPACK_DEBIAN_CASADI_DISPLAY_NAME "CasADi loaders")
set(CPACK_DEBIAN_CASADI_DESCRIPTION "Classes for loading problems defined using CasADi functions")
set(CPACK_DEBIAN_CASADI_GROUP "Extra")
set(CPACK_DEBIAN_EXTRA_PACKAGE_NAME "libalpaqa-extra")
set(CPACK_DEBIAN_EXTRA_DISPLAY_NAME "Extra solvers and loaders")
set(CPACK_DEBIAN_EXTRA_DESCRIPTION "Interfaces to additional solvers and problem loaders")
set(CPACK_DEBIAN_EXTRA_GROUP "Extra")
# Package dependencies
set(CPACK_DEBIAN_LIB_PACKAGE_DEPENDS "libc6 (>= 2.17), libgfortran5 (>= 10), libquadmath0 (>= 10)")
set(CPACK_COMPONENT_DEV_DEPENDS "lib;dl_dev")
set(CPACK_DEBIAN_DEV_PACKAGE_DEPENDS "libalpaqa (= ${PROJECT_VERSION}${PY_VERSION_SUFFIX}), libalpaqa-dl-dev (= ${PROJECT_VERSION}${PY_VERSION_SUFFIX})")
set(CPACK_DEBIAN_DEV_PACKAGE_SUGGESTS "libeigen3-dev (>= 3.4.0), libeigen3-dev (<< 3.4.1)")
set(CPACK_DEBIAN_DL_DEV_PACKAGE_DEPENDS "")
set(CPACK_DEBIAN_DL_DEV_PACKAGE_SUGGESTS "libalpaqa-dev (= ${PROJECT_VERSION}${PY_VERSION_SUFFIX})")
set(CPACK_DEBIAN_DEBUG_PACKAGE_DEPENDS "libalpaqa (= ${PROJECT_VERSION}${PY_VERSION_SUFFIX})")
set(CPACK_DEBIAN_BIN_PACKAGE_DEPENDS "libalpaqa (= ${PROJECT_VERSION}${PY_VERSION_SUFFIX}) libalpaqa-casadi (= ${PROJECT_VERSION}${PY_VERSION_SUFFIX}) libalpaqa-extra (= ${PROJECT_VERSION}${PY_VERSION_SUFFIX})")
set(CPACK_COMPONENT_BIN_DEPENDS "lib;casadi;extra")
set(CPACK_DEBIAN_MATLAB_PACKAGE_DEPENDS "libalpaqa (= ${PROJECT_VERSION}${PY_VERSION_SUFFIX}) libalpaqa-casadi (= ${PROJECT_VERSION}${PY_VERSION_SUFFIX})")
set(CPACK_COMPONENT_MATLAB_DEPENDS "lib;casadi")
set(CPACK_COMPONENT_MATLAB_DISABLED On)
# Source packages
set(CPACK_SOURCE_PACKAGE_FILE_NAME "${PROJECT_NAME}-${PROJECT_VERSION}${PY_VERSION_SUFFIX}")
set(CPACK_SOURCE_GENERATOR "TGZ;ZIP")
set(CPACK_SOURCE_IGNORE_FILES
    \\.git/
    build/
)
include(CPack)
